# app.yaml
# TODO: DELETE THIS FILE BECAUSE IT HAS THE APIs PUBLISHED. 
runtime: nodejs23

env_variables:
  PROJECT_ID: "branddna-firestore"
  LOCATION_ID: "us-central1"
  API_ENDPOINT: "us-central1-aiplatform.googleapis.com"
  GENERATE_CONTENT_API: "streamGenerateContent"
  BUCKET_NAME: "branddna-testing"
  DATABASE_ID: "branddnadb"
  SUPADATA_API_KEY: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6IjEifQ.eyJpc3MiOiJuYWRsZXMiLCJpYXQiOiIxNzQxMzYzMTA0IiwicHVycG9zZSI6ImFwaV9hdXRoZW50aWNhdGlvbiIsInN1YiI6Ijc0MmVjOTYwNzg4NDQzZjQ5ZWNjNTliNDExMDJiZDRjIn0.vuuE4v728jrwdt4gvmvMffay_RtK8XRIts_KB12HdJI"
  GEMINI_API_KEY: "AIzaSyDflz9EErhM8Th4LUYM0l6V2Mv9_i9D1z4"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /static
    static_dir: public
    secure: always

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env: standard
