# app.yaml
runtime: nodejs20

env_variables:
  PROJECT_ID: "google.com:branddna"
  LOCATION_ID: "us-central1"
  API_ENDPOINT: "us-central1-aiplatform.googleapis.com"
  GENERATE_CONTENT_API: "streamGenerateContent"
  BUCKET_NAME: "branddna-storage"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /static
    static_dir: public
    secure: always

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env: standard